[package]
name = "hex_to_rust"
version = "0.1.0"
edition = "2021"
description = "Convert wireshark hexdump to rust array"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
